package:
  name: limix_qep
  version: 0.1.8

requirements:
  build:
    - python
    - numpy
    - scipy
    - cython
    - setuptools
    - conda-build
    - limix_math
    - limix_tool
    - hcache

  run:
    - python
    - numpy
    - scipy
    - setuptools
    - cython
    - limix_math
    - limix_tool
    - hcache

about:
  home: http://www.ebi.ac.uk
  license: Private
